# -*- coding: utf-8 -*-
"""Exploración de los datos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HuVAtSxsSrU-pwMmGAjm9OTkWVFuztFP
"""

import pandas as pd
import matplotlib.pyplot as plt

# Cargar los datos
data_path = 'ARREGLO_DIRECTO.csv'
data = pd.read_csv(data_path, delimiter=';')

data['DURACION'] = pd.to_numeric(data['DURACION'], errors='coerce')

# Histograma de Duración
plt.figure(figsize=(10, 6))
plt.hist(data['DURACION'].dropna(), bins=30, color='blue', alpha=0.7)
plt.title('Distribución de la Duración de los Arreglos Directos')
plt.xlabel('Duración (días)')
plt.ylabel('Frecuencia')
plt.grid(True)
plt.show()

# Gráfico de barras para Causal de las Quejas
plt.figure(figsize=(12, 8))
data['CAUSAL'].value_counts().plot(kind='bar', color='green', alpha=0.7)
plt.title('Frecuencia de Causales de Quejas')
plt.xlabel('Causal')
plt.ylabel('Número de Casos')
plt.xticks(rotation=45, ha='right')
plt.grid(True)
plt.show()

# Gráfico de barras para Tipo de Producto
plt.figure(figsize=(12, 8))
data['TIPO_PRODUCTO'].value_counts().plot(kind='bar', color='orange', alpha=0.7)
plt.title('Frecuencia de Tipos de Productos en Quejas')
plt.xlabel('Tipo de Producto')
plt.ylabel('Número de Casos')
plt.xticks(rotation=45, ha='right')
plt.grid(True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Cargar los datos
data = pd.read_csv('ARREGLO_DIRECTO.csv', delimiter=';')

# Convertir fechas y limpiar datos
data['FECHA_REGISTRO'] = pd.to_datetime(data['FECHA_REGISTRO'], errors='coerce')
data['DURACION'] = pd.to_numeric(data['DURACION'], errors='coerce')

# Outliers en la duración
plt.figure(figsize=(10, 6))
sns.boxplot(x=data['DURACION'])
plt.title('Boxplot de Duración de los Arreglos Directos')
plt.xlabel('Duración (días)')
plt.show()

# Correlación entre duración y otras variables numéricas
# Por ejemplo, si 'VALOR_PRODUCTO' es una variable relevante
data['VALOR_PRODUCTO'] = pd.to_numeric(data['VALOR_PRODUCTO'], errors='coerce')
correlation_matrix = data[['DURACION', 'VALOR_PRODUCTO']].corr()
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.title('Mapa de Calor de Correlaciones')
plt.show()

# Tendencias de duración a lo largo del tiempo
data['AÑO_REGISTRO'] = data['FECHA_REGISTRO'].dt.year
plt.figure(figsize=(12, 6))
sns.lineplot(x='AÑO_REGISTRO', y='DURACION', data=data)
plt.title('Tendencia Anual de la Duración de los Arreglos Directos')
plt.xlabel('Año')
plt.ylabel('Duración Media (días)')
plt.show()